=== iij/mirai-toushi/jsonschema/xor_table_jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "xor_table",
  "description": "extract xor data from Mirai table.c",
  "type": "object",
  "properties": {
    "script_name": {
      "description": "script name",
      "type": "string",
      "enum": ["xor_table.py"]
    },
    "ghidra_current_program": {
      "description": "Ghidra currentProgram info",
      "type": "object",
      "properties": {
        "name": {
          "description": "file name",
          "type": "string"
        },
        "path": {
          "description": "file path",
          "type": "string"
        },
        "sha256": {
          "description": "file SHA256 hash",
          "type": "string"
        },
        "language_id": {
          "description": "program language name",
          "type": "string"
        },
        "image_base": {
          "description": "program image base address",
          "type": "string"
        },
        "min_addr": {
          "description": "program minimum address",
          "type": "string"
        },
        "max_addr": {
          "description": "program maximum address",
          "type": "string"
        }
      }
    },
    "table_lock_val_func": {
      "description": "Mirai table.c/table_lock_val() info",
      "type": "object",
      "properties": {
        "name": {
          "description": "function name",
          "type": "string"
        },
        "entrypoint": {
          "description": "function entrypoint",
          "type": "string"
        },
        "table_key": {
          "description": "table.c xor key (1 byte)",
          "type": "string",
          "pattern": "^0x[0-9a-f]{2}$"
        },
        "table_original_key": {
          "description": "table.c original xor key (4 bytes)",
          "type": "string",
          "pattern": "^0x[0-9a-f]{8}$"
        }
      }
    },
    "table_init_func": {
      "description": "Mirai table.c/table_init() info",
      "type": "object",
      "properties": {
        "name": {
          "description": "function name",
          "type": "string"
        },
        "entrypoint": {
          "description": "function entrypoint",
          "type": "string"
        },
        "tables_sha256": {
          "description": "tables SHA256 hash",
          "type": "string"
        },
        "tables_count": {
          "description": "number of tables",
          "type": "number"
        },
        "tables_int_count": {
          "description": "number of type int tables",
          "type": "number"
        },
        "tables_str_count": {
          "description": "number of type str tables",
          "type": "number"
        },
        "tables": {
          "description": "xor data using for Mirai configuration",
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "id": {
                  "description": "data id defined at table.h",
                  "type": "number"
                },
                "type": {
                  "description": "data type",
                  "type": "string"
                },
                "int_data": {
                  "description": "type int data (maybe port number 0-65535)",
                  "type": "number",
                  "maximum": 65535
                },
                "str_data": {
                  "description": "type str data",
                  "type": "string",
                  "maxLength": 1024
                },
                "table_addr": {
                  "description": "table address",
                  "type": "string"
                },
                "refs": {
                  "description": "function/address of data reference source",
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "func": {
                          "description": "function name of data reference source",
                          "type": "string"
                        },
                        "addr": {
                          "description": "address of data reference source",
                          "type": "string"
                        }
                      }
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== iij/mirai-toushi/sample/xor_table.json
{
  "script_name": "xor_table.py", 
  "ghidra_current_program": {
    "name": "sample.i586", 
    "path": "/home/remnux/sample.i586", 
    "sha256": "daf75e88ac6fc869350b426a10f0e8d9588b016e420485e390c6d0388e0aa90e", 
    "language_id": "x86:LE:32:default", 
    "image_base": "08048000", 
    "min_addr": "08048000", 
    "max_addr": "_elfSectionHeaders::0000027f"
  }, 
  "table_lock_val_func": {
    "name": "table_lock_val", 
    "entrypoint": "08050f80", 
    "table_key": "0x22", 
    "table_original_key": "0xdeadbeef"
  }, 
  "table_init_func": {
    "name": "table_init", 
    "entrypoint": "08051080", 
    "tables_sha256": "5c4a784a20ca5269802f1b39be5a9b5ca9e2fe9deca5285467788e4ba95182dd", 
    "tables_count": 50, 
    "tables_int_count": 2, 
    "tables_str_count": 48, 
    "tables": [
      {
        "id": 3, 
        "type": "str", 
        "str_data": "example.com", 
        "table_addr": "080565d8", 
        "refs": [
          {
            "func": "resolve_cnc_addr", 
            "addr": "0804e552"
          }
        ]
      }, 
      {
        "id": 4, 
        "type": "int", 
        "int_data": 23, 
        "table_addr": "080565e0", 
        "refs": [
          {
            "func": "resolve_cnc_addr", 
            "addr": "0804e5a9"
          }
        ]
      }, 
      {
        "id": 18, 
        "type": "str", 
        "str_data": "example.net", 
        "table_addr": "08056650", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "08050dcb"
          }
        ]
      }, 
      {
        "id": 19, 
        "type": "int", 
        "int_data": 48101, 
        "table_addr": "08056658", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "08050e11"
          }
        ]
      }, 
      {
        "id": 2, 
        "type": "str", 
        "str_data": "listening tun0", 
        "table_addr": "080565d0", 
        "refs": [
          {
            "func": "main", 
            "addr": "0804ea13"
          }
        ]
      }, 
      {
        "id": 5, 
        "type": "str", 
        "str_data": "https://example.com/", 
        "table_addr": "080565e8", 
        "refs": []
      }, 
      {
        "id": 6, 
        "type": "str", 
        "str_data": "/proc/", 
        "table_addr": "080565f0", 
        "refs": [
          {
            "func": "killer_kill_by_port", 
            "addr": "0804d833"
          }, 
          {
            "func": "killer_kill_by_port", 
            "addr": "0804d890"
          }, 
          {
            "func": "killer_kill_by_port", 
            "addr": "0804d91e"
          }, 
          {
            "func": "killer_kill_by_port", 
            "addr": "0804d9d6"
          }, 
          {
            "func": "killer_init", 
            "addr": "0804dd27"
          }, 
          {
            "func": "killer_init", 
            "addr": "0804de20"
          }, 
          {
            "func": "killer_init", 
            "addr": "0804dedf"
          }, 
          {
            "func": "killer_init", 
            "addr": "0804df25"
          }
        ]
      }, 
      {
        "id": 7, 
        "type": "str", 
        "str_data": "/exe", 
        "table_addr": "080565f8", 
        "refs": [
          {
            "func": "killer_kill_by_port", 
            "addr": "0804d8cc"
          }, 
          {
            "func": "killer_init", 
            "addr": "0804dd6c"
          }, 
          {
            "func": "killer_init", 
            "addr": "0804df0e"
          }
        ]
      }, 
      {
        "id": 8, 
        "type": "str", 
        "str_data": " (deleted)", 
        "table_addr": "08056600", 
        "refs": []
      }, 
      {
        "id": 9, 
        "type": "str", 
        "str_data": "/fd", 
        "table_addr": "08056608", 
        "refs": [
          {
            "func": "killer_kill_by_port", 
            "addr": "0804d95a"
          }, 
          {
            "func": "killer_kill_by_port", 
            "addr": "0804da12"
          }
        ]
      }, 
      {
        "id": 10, 
        "type": "str", 
        "str_data": ".anime", 
        "table_addr": "08056610", 
        "refs": [
          {
            "func": "killer_init", 
            "addr": "0804dfc0"
          }
        ]
      }, 
      {
        "id": 11, 
        "type": "str", 
        "str_data": "/status", 
        "table_addr": "08056618", 
        "refs": [
          {
            "func": "killer_init", 
            "addr": "0804df54"
          }
        ]
      }, 
      {
        "id": 12, 
        "type": "str", 
        "str_data": "REPORT %s:%s", 
        "table_addr": "08056620", 
        "refs": [
          {
            "func": "killer_init", 
            "addr": "0804e12c"
          }
        ]
      }, 
      {
        "id": 13, 
        "type": "str", 
        "str_data": "HTTPFLOOD", 
        "table_addr": "08056628", 
        "refs": [
          {
            "func": "killer_init", 
            "addr": "0804e141"
          }
        ]
      }, 
      {
        "id": 14, 
        "type": "str", 
        "str_data": "LOLNOGTFO", 
        "table_addr": "08056630", 
        "refs": [
          {
            "func": "killer_init", 
            "addr": "0804e156"
          }
        ]
      }, 
      {
        "id": 15, 
        "type": "str", 
        "str_data": "\\x58\\x4D\\x4E\\x4E\\x43\\x50\\x46\\x22", 
        "table_addr": "08056638", 
        "refs": [
          {
            "func": "killer_init", 
            "addr": "0804e16b"
          }
        ]
      }, 
      {
        "id": 16, 
        "type": "str", 
        "str_data": "zollard", 
        "table_addr": "08056640", 
        "refs": [
          {
            "func": "killer_init", 
            "addr": "0804e180"
          }
        ]
      }, 
      {
        "id": 17, 
        "type": "str", 
        "str_data": "GETLOCALIP", 
        "table_addr": "08056648", 
        "refs": []
      }, 
      {
        "id": 20, 
        "type": "str", 
        "str_data": "shell", 
        "table_addr": "08056660", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "080506e4"
          }
        ]
      }, 
      {
        "id": 21, 
        "type": "str", 
        "str_data": "enable", 
        "table_addr": "08056668", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "08050b02"
          }
        ]
      }, 
      {
        "id": 22, 
        "type": "str", 
        "str_data": "system", 
        "table_addr": "08056670", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "08050997"
          }
        ]
      }, 
      {
        "id": 23, 
        "type": "str", 
        "str_data": "sh", 
        "table_addr": "08056678", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "08050a89"
          }
        ]
      }, 
      {
        "id": 24, 
        "type": "str", 
        "str_data": "/bin/busybox MIRAI", 
        "table_addr": "08056680", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "08050a10"
          }
        ]
      }, 
      {
        "id": 25, 
        "type": "str", 
        "str_data": "MIRAI: applet not found", 
        "table_addr": "08056688", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "080505cf"
          }
        ]
      }, 
      {
        "id": 26, 
        "type": "str", 
        "str_data": "ncorrect", 
        "table_addr": "08056690", 
        "refs": [
          {
            "func": "scanner_init", 
            "addr": "08050586"
          }
        ]
      }, 
      {
        "id": 27, 
        "type": "str", 
        "str_data": "/bin/busybox ps", 
        "table_addr": "08056698", 
        "refs": []
      }, 
      {
        "id": 28, 
        "type": "str", 
        "str_data": "/bin/busybox kill -9 ", 
        "table_addr": "080566a0", 
        "refs": []
      }, 
      {
        "id": 29, 
        "type": "str", 
        "str_data": "TSource Engine Query", 
        "table_addr": "080566a8", 
        "refs": [
          {
            "func": "attack_udp_vse", 
            "addr": "0804cc39"
          }
        ]
      }, 
      {
        "id": 30, 
        "type": "str", 
        "str_data": "/etc/resolv.conf", 
        "table_addr": "080566b0", 
        "refs": [
          {
            "func": "attack_udp_dns", 
            "addr": "0804cfd6"
          }
        ]
      }, 
      {
        "id": 31, 
        "type": "str", 
        "str_data": "nameserver ", 
        "table_addr": "080566b8", 
        "refs": [
          {
            "func": "attack_udp_dns", 
            "addr": "0804d02b"
          }
        ]
      }, 
      {
        "id": 32, 
        "type": "str", 
        "str_data": "Connection: keep-alive", 
        "table_addr": "080566c0", 
        "refs": [
          {
            "func": "attack_app_http", 
            "addr": "08048886"
          }
        ]
      }, 
      {
        "id": 33, 
        "type": "str", 
        "str_data": "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
        "table_addr": "080566c8", 
        "refs": [
          {
            "func": "attack_app_http", 
            "addr": "080488f1"
          }
        ]
      }, 
      {
        "id": 34, 
        "type": "str", 
        "str_data": "Accept-Language: en-US,en;q=0.8", 
        "table_addr": "080566d0",
